import {
  AppStateInputs,
  DEFAULT_DETAILED_EXPENSES_STATE,
  DEFAULT_CHARITY_SETTINGS,
  DEFAULT_GUARDRAIL_SETTINGS,
  DEFAULT_BUCKET_STRATEGY_SETTINGS,
} from '../../types';

/**
 * Isolated, realistic Sample Demonstration Plan for Ephemeral Demo Sandbox Mode.
 * This plan runs in-memory only and is completely isolated from the user's real plan.
 */
export const SAMPLE_DEMO_PLAN: AppStateInputs = {
  isConfigured: true,
  isSingleFiler: false,
  simulationStartYear: 2026,
  simulateSurvivor: false,
  you: {
    name: 'Sample Primary',
    birthDate: '1961-04-15',
    plannedRetirementAge: 65,
    plannedRetirementMonth: 4,
    targetSSClaimingAge: 67,
    estimatedPIA: 3200,
    activeSalary: 145000,
    preMedicareMonthlyPremium: 650,
    longevityAge: 90,
  },
  wife: {
    name: 'Sample Spouse',
    birthDate: '1964-08-20',
    plannedRetirementAge: 65,
    plannedRetirementMonth: 8,
    targetSSClaimingAge: 67,
    estimatedPIA: 2200,
    activeSalary: 65000,
    preMedicareMonthlyPremium: 650,
    longevityAge: 92,
  },
  portfolio: {
    yourPreTaxIRA: 950000,
    yourRothIRA: 220000,
    yourTaxableBrokerage: 420000,
    yourTaxableBasis: 300000,
    yourCash: 75000,
    wifePreTaxIRA: 480000,
    wifeRothIRA: 130000,
    wifeTaxableBrokerage: 210000,
    wifeTaxableBasis: 160000,
    wifeCash: 45000,
    taxableDividendYield: 0.02,
    taxableNonQualifiedPortion: 0.20,
  },
  jurisdiction: {
    currentState: 'MD',
    targetState: 'FL',
    relocationYear: 2028,
  },
  growthAssumptions: {
    equityReturnRate: 0.07,
    fixedIncomeReturnRate: 0.04,
    cpiInflationRate: 0.025,
    healthcareInflationRate: 0.05,
    preTaxEquityPortion: 0.60,
    taxableEquityPortion: 0.75,
    rothEquityPortion: 1.00,
    cashYieldRate: 0.035,
    minCashReserveDollars: 100000,
  },
  annualLivingExpenses: 96000,
  annualRothConversion: 50000,
  rothConversionStartYear: 2027,
  rothConversionEndYear: 2033,
  rothConversionStrategy: 'fill-to-target',
  rothConversionTargetValue: 125000,
  customRothScenarios: [],
  activeCustomScenarioId: null,
  monteCarloSettings: {
    mode: 'monte-carlo',
    equityVolatility: 0.15,
    fixedIncomeVolatility: 0.05,
    correlation: 0.15,
    trials: 1000,
    seed: null,
    randomizeCPI: true,
    constantCPIRate: null,
    enableRegimeSwitching: true,
    historicalSamplingStrategy: 'hybrid',
    calibrateHistoricalMeans: true,
    stressTest: {
      enabled: false,
      mode: 'absolute',
      overrides: [],
    },
  },
  useDetailedExpenses: false,
  detailedExpenses: JSON.parse(JSON.stringify(DEFAULT_DETAILED_EXPENSES_STATE)),
  charitySettings: DEFAULT_CHARITY_SETTINGS,
  actualTracking: {},
  guardrailSettings: DEFAULT_GUARDRAIL_SETTINGS,
  bucketSettings: DEFAULT_BUCKET_STRATEGY_SETTINGS,
};
